// Constants
export const POST_NEW_THING = 'POST_NEW_THING'
export const RECEIVE_CURRENT_THING = 'RECEIVE_CURRENT_THING'
export const RECEIVE_THING_LIST = 'RECEIVE_THING_LIST'
export const RECEIVE_THINGS = 'RECEIVE_THINGS'
export const REQUEST_CURRENT_THING = 'REQUEST_CURRENT_THING'
export const REQUEST_THING_LIST = 'REQUEST_THING_LIST'
