// Constants
export const REQUEST_LOG_IN = 'REQUEST_LOG_IN'
export const RECEIVE_LOG_IN = 'RECEIVE_LOG_IN'
export const RECEIVE_LOG_IN_ERROR = 'RECEIVE_LOG_IN_ERROR'
export const REQUEST_LOG_OUT = 'REQUEST_LOG_OUT'
export const RECEIVE_LOG_OUT = 'RECEIVE_LOG_OUT'
