// Constants
export const RECEIVE_LOG_IN = 'RECEIVE_LOG_IN'
export const RECEIVE_LOG_IN_ERROR = 'RECEIVE_LOG_IN_ERROR'
export const RECEIVE_LOG_OUT = 'RECEIVE_LOG_OUT'
export const RECEIVE_NEW_USER = 'RECEIVE_NEW_USER'
export const RECEIVE_NEW_USER_ERROR = 'RECEIVE_NEW_USER_ERROR'
export const REQUEST_LOG_IN = 'REQUEST_LOG_IN'
export const REQUEST_LOG_OUT = 'REQUEST_LOG_OUT'
export const REQUEST_NEW_USER = 'REQUEST_NEW_USER'
