// Constants
export const POST_NEW_REVIEW = 'POST_NEW_REVIEW'
export const RECEIVE_REVIEW = 'RECEIVE_REVIEW'
export const RECEIVE_REVIEWS = 'RECEIVE_REVIEWS'
export const REQUEST_REVIEW = 'REQUEST_REVIEW'
export const REQUEST_REVIEWS = 'REQUEST_REVIEWS'
