// Constants
export const LIKE_REVIEW_ERROR = 'LIKE_REVIEW_ERROR'
export const POST_NEW_REVIEW = 'POST_NEW_REVIEW'
export const RECEIVE_CURRENT_REVIEW = 'RECEIVE_CURRENT_REVIEW'
export const RECEIVE_CURRENT_REVIEW_ERROR = 'RECEIVE_CURRENT_REVIEW_ERROR'
export const RECEIVE_REVIEW_FEED = 'RECEIVE_REVIEW_FEED'
export const RECEIVE_REVIEWS = 'RECEIVE_REVIEWS'
export const REQUEST_CURRENT_REVIEW = 'REQUEST_CURRENT_REVIEW'
export const REQUEST_REVIEW_FEED = 'REQUEST_REVIEW_FEED'
